### ISSUE TITLE
Making more than 1 GraphQL endpoint

### ISSUE THREAD

**Issue by GGorAA** [aPureBase/KGraphQL#126]
Hello,
I need to make two different endpoints for GraphQL, for example `/v1/graphql` and `/v2/graphql`, for different versions of API. How can I do that?

**Comment by jeggy** [comment]
I guess you are using the ktor feature?

As by using GraphQL you normally wouldn't need multiple versions of a schema, normally you would use the [deprecation](https://kgraphql.io/Reference/deprecation/) to incrementally change your schema. And because of this I do not think this is something that kgraphql-ktor will add support for.

But if this is something that you do want to have, you could do it without the use of our ktor feature. I have written an example below:

```kotlin
fun main() {
    embeddedServer(CIO, port = 8000) {
        val gqlV1 = KGraphQL.schema {
            query("hello") {
                resolver { -> "old" }
            }
        }
        val gqlV2 = KGraphQL.schema {
            query("hello") {
                resolver { -> "new" }
            }
        }
        install(ContentNegotiation) { json() }
        routing {
            post("/v1/graphql") {
                val req = call.receive<GraphqlRequest>()
                val context = context { /* Build your context */ }
                call.respond(gqlV1.execute(req.query, req.variables.toString(), context))
            }
            post("/v2/graphql") {
                val req = call.receive<GraphqlRequest>()
                val context = context { /* Build your context */ }
                call.respond(gqlV2.execute(req.query, req.variables.toString(), context))
            }
        }
    }.start(wait = true)
}
```
