### ISSUE TITLE
Since 0.6.0, Introspection includes SchemaProxy and LookupSchema.

### ISSUE THREAD

**Issue by Ischca** [aPureBase/KGraphQL#45]
There is no problem with 0.5.1.

In version 0.6.0 and later, introspection includes SchemaProxy and LookupSchema.
Is this an intended change?
In this state, [GraphQL Code Generator](https://graphql-code-generator.com/) fails to execute.

**Comment by jeggy** [comment]
This is probably because of me adding union types to the introspection, I did only test it with the Apollo's Playground. 

I have found that this change also broke the [JS GraphQL IntelliJ Plugin](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin) integration. 

There shouldn't be any other changes in 0.6.x, so you could just stay in version 0.5.1 until 0.7.x get's released. I will try to fix this asap.
